"""Engine-neutral localization adapter contracts and implementations."""

from .contracts import (
    CANDIDATE_SCHEMA_VERSION,
    CONTENT_FINGERPRINT_SCHEMA_VERSION,
    COVERAGE_DIGEST_SCHEMA_VERSION,
    COVERAGE_REVIEW_SCHEMA_VERSION,
    COVERAGE_SCHEMA_VERSION,
    ENGINE_ADAPTER_PROTOCOL_VERSION,
    OCCURRENCE_SCHEMA_VERSION,
    VALIDATION_SCHEMA_VERSION,
    WRITEBACK_PLAN_SCHEMA_VERSION,
    RelocationResult,
    ValidatedTranslation,
    ValidationResult,
    WritebackOperation,
    WritebackPlan,
    Candidate,
    CandidateInventory,
    EngineAdapter,
    EngineCapabilities,
    InventoryPolicy,
    LocalizationMode,
    Occurrence,
    OpaqueLocator,
    ProjectDiscovery,
    ProjectDiscoveryRequest,
    SourceDocument,
)
from .coverage import (
    CoverageFreshness,
    CoverageReport,
    ReviewValidation,
    build_coverage_report,
    build_review_template,
    export_coverage_package,
    load_review_record,
    validate_coverage_report_freshness,
    validate_review_record,
)
from .writeback import (
    WritebackPlanError,
    render_writeback_plan,
    source_snapshot_fingerprint,
    validate_writeback_plan,
)
from .renpy import (
    ADAPTER_VERSION as RENPY_ADAPTER_VERSION,
    RenPyAdapter,
    RenPyTranslationSnapshot,
    build_translation_snapshot,
)

__all__ = [
    "CANDIDATE_SCHEMA_VERSION",
    "CONTENT_FINGERPRINT_SCHEMA_VERSION",
    "COVERAGE_DIGEST_SCHEMA_VERSION",
    "COVERAGE_REVIEW_SCHEMA_VERSION",
    "COVERAGE_SCHEMA_VERSION",
    "ENGINE_ADAPTER_PROTOCOL_VERSION",
    "OCCURRENCE_SCHEMA_VERSION",
    "RENPY_ADAPTER_VERSION",
    "VALIDATION_SCHEMA_VERSION",
    "WRITEBACK_PLAN_SCHEMA_VERSION",
    "RelocationResult",
    "ValidatedTranslation",
    "ValidationResult",
    "WritebackOperation",
    "WritebackPlan",
    "Candidate",
    "CandidateInventory",
    "CoverageFreshness",
    "CoverageReport",
    "EngineAdapter",
    "EngineCapabilities",
    "InventoryPolicy",
    "LocalizationMode",
    "Occurrence",
    "OpaqueLocator",
    "ProjectDiscovery",
    "ProjectDiscoveryRequest",
    "RenPyAdapter",
    "RenPyTranslationSnapshot",
    "ReviewValidation",
    "SourceDocument",
    "build_coverage_report",
    "build_review_template",
    "build_translation_snapshot",
    "export_coverage_package",
    "load_review_record",
    "WritebackPlanError",
    "render_writeback_plan",
    "source_snapshot_fingerprint",
    "validate_writeback_plan",
    "validate_coverage_report_freshness",
    "validate_review_record",
]
